import type { Equipment } from './types';

export const EQUIPMENT_LIST: Equipment[] = [
    { id: 1, name: 'Continuous Hot Extraction Equipment' },
    { id: 2, name: 'Percolator' },
    { id: 3, name: 'Tincture Press' },
    { id: 4, name: 'Grinding Mill' },
    { id: 5, name: 'Disintegrator' },
    { id: 6, name: 'Tablet Machine' },
    { id: 7, name: 'Tablet Hardness Tester' },
    { id: 8, name: 'Granulating Sieve Set' },
    { id: 9, name: 'Tablet Counter Small Size' },
    { id: 10, name: 'Friability Tester' },
    { id: 11, name: 'Distillation Equipment for Distilled Water (Glass)' },
    { id: 12, name: 'Disintegration Test Unit' },
    { id: 13, name: 'Sintered glass filters for bacterial proof Filtration (Four different grades)' },
    { id: 14, name: 'Millipore filter (3 Grades) 2 each' },
    { id: 15, name: 'Autoclave' },
    { id: 16, name: 'Hot Air Sterilizer' },
    { id: 17, name: 'Incubator' },
    { id: 18, name: 'Tube Filling and Sealing Equipments' },
    { id: 19, name: 'Prescription Balance/Dispensing Balance' },
    { id: 20, name: 'Pill Tiles' },
    { id: 21, name: 'Balance Torsion type with removable glass pan sensitivity, 30 mgm' },
    { id: 22, name: 'Water Deionization Unit' },
    { id: 23, name: 'Pressure Cookers' },
    { id: 24, name: 'Aseptic Cabinet' },
    { id: 25, name: 'Blender' },
    { id: 26, name: 'Sieves Set (Pharmacopoeia Standard)' },
    { id: 27, name: 'Laboratory Centrifuge' },
    { id: 28, name: 'Ointment Slabs' },
    { id: 29, name: 'Ointment Spatulas' },
    { id: 30, name: 'Pestle and Mortar (Porcelain)' },
    { id: 31, name: 'Pestle and Mortar (Glass)' },
    { id: 32, name: 'Suppository Moulds of 3 size' },
    { id: 33, name: 'Horn Spatulas' },
    { id: 34, name: 'Refrigerator' },
    { id: 35, name: 'Macerating Jar' },
    { id: 36, name: 'Presses' },
    { id: 37, name: 'Chopping board & Knife' },
    { id: 38, name: 'Water bath Metal circular' },
    { id: 39, name: 'Succession Machine (Automatic)' },
    { id: 40, name: 'Potentizer (Automatic)' },
    { id: 41, name: 'Evaporating dishes' },
    { id: 42, name: 'Pycnometer' },
    { id: 43, name: 'Storage Tank' },
    { id: 44, name: 'Ointment Pots' },
    { id: 45, name: 'Barometer' },
    { id: 46, name: 'General Glassware' },
    { id: 47, name: 'Chemical Appliances Laboratory Facilities' },
];
